### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by pakastin** [pakastin/frzr-dom#4]
- [ ] add `replaceChild`
- [ ] do not render `parent` property
- [ ] add `querySelector`, `getElementById`, `getElementsByClassName`, ...
- [x] add `innerHTML` & `outerHTML`
- [x] create tests
- [x] run FRZR test
- [x] remove hidden characters
- [ ] only ignore content from void HTMLElements
